"""
backend/exporter.py

Exports HealthSense AI reports.
Supports Markdown export with unique filenames.
"""

from datetime import datetime
from pathlib import Path

from backend.constants import EXPORTS_DIR
from backend.formatter import generate_report


class ReportExporter:
    """
    Handles exporting reports generated by HealthSense AI.
    """

    def __init__(self):
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

    def export_markdown(
        self,
        question: str,
        response: str,
    ) -> Path:
        """
        Export a Markdown report.

        Returns:
            Path to the exported report.
        """

        report = generate_report(question, response)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        output_file = EXPORTS_DIR / f"HealthSense_Report_{timestamp}.md"

        output_file.write_text(
            report,
            encoding="utf-8",
        )

        return output_file


if __name__ == "__main__":

    exporter = ReportExporter()

    path = exporter.export_markdown(
        question="What causes headaches?",
        response="Headaches commonly occur due to stress, dehydration, or lack of sleep."
    )

    print("=" * 50)
    print("✅ Report exported successfully!")
    print(path)