"""
backend/formatter.py

Formats AI responses and generates professional reports
for HealthSense AI.
"""

from datetime import datetime

from backend.constants import (
    APP_NAME,
    APP_VERSION,
    APP_TAGLINE,
    MEDICAL_DISCLAIMER,
    DEFAULT_WELLNESS_ACTIONS,
)


def format_ai_response(response: str) -> str:
    """
    Clean and finalize the AI response before displaying it.
    """

    response = response.strip()

    if "disclaimer" not in response.lower():
        response += (
            f"\n\n## 📌 Medical Disclaimer\n\n"
            f"{MEDICAL_DISCLAIMER}"
        )

    return response


def generate_report(question: str, response: str) -> str:
    """
    Generate a professional Markdown report.
    """

    timestamp = datetime.now().strftime("%d %B %Y | %I:%M %p")

    wellness_actions = "\n".join(
        f"- {item}" for item in DEFAULT_WELLNESS_ACTIONS
    )

    report = f"""# 🩺 {APP_NAME}

### {APP_TAGLINE}

**Version:** {APP_VERSION}

**Generated:** {timestamp}

---

# ❓ User Question

{question}

---

# 🤖 AI Response

{response}

---

# 🌿 Daily Wellness Checklist

{wellness_actions}

---

# 📌 Medical Disclaimer

{MEDICAL_DISCLAIMER}

---

*Generated by HealthSense AI using Groq LLM.*
"""

    return report


if __name__ == "__main__":

    sample_question = "What causes headaches?"

    sample_response = """
## 🩺 Explanation

Headaches can have many common causes.

## ⚠️ Possible Causes

- Stress
- Dehydration
- Lack of sleep
"""

    print(generate_report(sample_question, sample_response))