"""
frontend/report_view.py

Displays a professional report preview before export.
"""

from datetime import datetime

import streamlit as st


def show_report_preview(question: str, response: str):
    """
    Display a beautiful report preview.
    """

    st.markdown("# 📄 Health Report Preview")

    st.markdown("---")

    st.markdown("## 🩺 HealthSense AI")

    st.caption("AI-Powered Educational Health Report")

    st.write(f"**Generated:** {datetime.now().strftime('%d %B %Y, %I:%M %p')}")

    st.markdown("---")

    st.subheader("❓ User Question")

    st.info(question)

    st.subheader("🤖 AI Response")

    st.markdown(response)

    st.markdown("---")

    st.subheader("🌿 Wellness Checklist")

    checklist = [
        "💧 Stay hydrated",
        "😴 Get enough sleep",
        "🥗 Eat balanced meals",
        "🏃 Stay physically active",
        "👨‍⚕️ Consult a healthcare professional if symptoms persist or worsen",
    ]

    for item in checklist:
        st.checkbox(item, value=True, disabled=True)

    st.markdown("---")

    st.warning(
        """
        **Medical Disclaimer**

        This report is generated by an AI system for educational purposes only.
        It is not a medical diagnosis and should not replace professional medical advice.
        """
    )

    st.download_button(
        label="⬇️ Download Report",
        data=response,
        file_name="HealthSense_Report.md",
        mime="text/markdown",
        use_container_width=True,
    )